### ISSUE TITLE
Fix redundant roads.

### ISSUE THREAD

**Issue by GuguKatze** [bencbartlett/Overmind#102]
Overmind is often building 2 or 3 roads between the same startPos and andPos.

Solution: RoadPlanner's costMatrix needs to contain existing roads as well as roads planned (even if planned during the same tick). Weight existing and planned roads in a way so new roads are only built if truly beneficial.

**Comment by Coolfeather2** [comment]
This is already the intended mechanic with it being truly beneficial already

**Comment by GuguKatze** [comment]
How is this beneficial?
http://666kb.com/i/e26ptiycxpp8fcczy.png
http://666kb.com/i/e26ptpk41pdfgd972.png

**Comment by Coolfeather2** [comment]
It's not that the path is redundant, it's due to being the same length and cost when re-pathing the road after cache is cleared

**Comment by GuguKatze** [comment]
Then just give really existing roads (in the Screeps world) a slightly lower weight in the cM when re-pathing? Where is the issue? We save 100s of ticks and energy ...

**Comment by bencbartlett** [comment]
The roads shown in that room are not redundant because only one path is actively maintained. We discussed the future solution in Slack -- new road network logic will be introduced in a future update which will include changes to transporter logic, link placement, and road routing.
