### ISSUE TITLE
BUG: Room stuck in bootstrap, queen stuck idle, lab stuck, no miners spawned too

### ISSUE THREAD

**Issue by zGeneral** [bencbartlett/Overmind#122]
## Issue summary
Room stuck, no miners spawns => stuck in bootstrap mode
queen stuck doing nothing

### Description of issue:

console kept showing the following
stuck in state 2 for 51 ticks, rebuilding reaction queue and reverting to idle state!

room recovered after destroying the labs
once destroyed, queen started working
spawners made miners... everything just worked!

### Error message:

```
// Console output:

```

```
// Offending line:

```

### Other information:
- Overmind version: *{found in package.json or by typing `info()` into console}*
    - Commit hash: *{optional, but helpful: include the commit hash (if known)}*

**Comment by zGeneral** [comment]
I think the bug is related directly to the queen

the queen was confused and did not fill extensions (because of labs, will have to look into its lab filling code)
once the labs were destroyed, the confusion was lifted, extensions got filled, miners spawned, bootstrap flag removed, everything back to normal

**Comment by NekoKetsu** [comment]
Same here :(
