### ISSUE TITLE
TypeError: Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by Coolfeather2** [bencbartlett/Overmind#14]
### Description of issue:

`TypeError: Cannot read property 'store' of undefined`
Does not seem to effect bot

Line 163 of TerminalNetwork.ts

### Steps to reproduce:

Compile latest release

### Error message:

```
// Console output:

main:23062
        let terminalNearCapacity = _.sum(terminal.store) > 0.9 * terminal.storeCapacity;
                                                  ^

TypeError: Cannot read property 'store' of undefined
    at TerminalNetwork.sellExcess (main:23062:51)
    at TerminalNetwork.run (main:23189:14)
    at _Overmind.run (main:24036:3343)
    at main (main:24126:14)
    at Object.wrap (main:6038:12)
    at Object.loop (main:24132:21)
    at __mainLoop:1:52
    at sigintHandlersWrap (vm.js:98:15)
```

### Other information:
- Overmind version: `0.3.1`
    - Commit hash: `030726216cb195f4b0c04ea44edcb044f095956f`
- Issue is with dependency: Yes?

**Comment by rooklion** [comment]
To fix
Line 296 in TerminalNetwork.ts can be changed to:

if (terminalToSellExcess) this.sellExcess(terminalToSellExcess);

**Comment by bencbartlett** [comment]
[Fixed in a recent commit](https://github.com/bencbartlett/Overmind/commit/8de8d8fafc262ab29d689d85486e03b4c3ee5ce7#diff-b5e4ef687527374f2dcadddccb0abdf9L296), thanks.
