### ISSUE TITLE
link based miner fails to operate if colony side link doesn't exist

### ISSUE THREAD

**Issue by ikiris** [bencbartlett/Overmind#159]
### Description of issue:
Colony can freeze in unrecoverable bootstrap if miner manages to have a link set up before the colony has one operational or the colony side one is destroyed.

### Suggested fix (optional):
colony could track if viable receive link exists

### Other information:
- Overmind version: current dev with a few tweaks.

**Comment by bencbartlett** [comment]
should be fixed now
