### ISSUE TITLE
failure to assign invasion defense spawn request to nearest colony when recovering + colonizing a room

### ISSUE THREAD

**Issue by ikiris** [bencbartlett/Overmind#160]
### Issue summary
Failling to spawn defenders for a room being colonized.

### Description of issue:

Looks like logistics : spawngroup is failling to find any valid spawn points for a room being colonized and/or to low level to spawn defenders.

### Steps to reproduce:
Be near Tigga with weaker rooms :)

### Error message:

```
[5:17:16 PM][shard2]ERROR   24254542 |    at SpawnGroup.init (main:26939:21)                  | Could not enqueue creep with role hydralisk in E7S54 for Overlord [invasionDefense:26ea0e>rangedDefense]!
[5:17:19 PM][shard2]WARNING 24254543 No colonies meet the requirements for SpawnGroup: invasionDefense:26ea0e>rangedDefense:SG

```

```
// Offending line:

```

### Suggested fix (optional):
I tried to walk through the code myself, but there's not a lot of debug entry here that I can find to determine what state the object is in which tracks the valid options for valid hatchery / colonies to spawn from for a given room at the time.

### Other information:
effectively running dev version with some modifications.
‣ Version:        Overmind v0.5.2
‣ Checksum:       0x0
‣ Assimilated:    No (clearance code: null) [WIP]
‣ Operating mode: automatic

**Comment by bencbartlett** [comment]
If this is on the dev branch, then I broke spawn groups in some cases a week or two ago. (Currently they're constantly screaming at me in console every time overmind tries to place a distant power mining directive) I'm planning to rework them in the near future, but until then they're gonna be bugged
