### ISSUE TITLE
Pioneers and new colonies

### ISSUE THREAD

**Issue by paralyser** [bencbartlett/Overmind#29]
## Feature request summary
Atm a fresh RC1 will begin starting the production of a queen, than drones, we could switch them, to spare some ticks.
Pioneers: With the current settings we will have 4 pioneers building up a new spawn, if they are finished they are split equally between drones and workers. Would be a faster method, to split them as 1 queen, and 3 drones, so we can give a kickstart to the fresh colony.
### Motivation:

To speed up low rc s catch up mechanism for fresh spawns, where is no opportunity to incubate.

**Comment by bencbartlett** [comment]
This has been fixed/added a few commits ago. Thanks for pointing it out!
