### ISSUE TITLE
Spawn blocking

### ISSUE THREAD

**Issue by paralyser** [bencbartlett/Overmind#30]
### Motivation:
Would be useful against safe mode rooms without towers, or with empty towers. Would work as a swarm.

### Description:
In some cases the safe modes are saving our opponents/enemies from us, forcing us to wait until safe mode Ends. The swarming tactic would block the spawns, preventing our opponent from spawning new creeps, forcing him/her to not to be able to recuperate. The swarm creeps could have only 1 part - moving. So they would be cheap, and effective. They would work as a counter-safe mode team. 
The swarm in work: They will occupy every spot near the enemy spawn, disabling the spawning.  Numbers may vary / they will need constant reinforcements.

**Comment by GuguKatze** [comment]
Enemy creeps become non-blocking in safe-mode. This won't work. Ironically, Overmind gets blocked that way as it is not ignoring hostile creeps when searching for paths.

See https://docs.screeps.com/api/#StructureController
"When safe mode is active, all hostile creeps become visually transparent and passable - your creeps can move through them freely (but not vice versa)."
