### ISSUE TITLE
RCL3 Bugs

### ISSUE THREAD

**Issue by paralyser** [bencbartlett/Overmind#31]
## Issue summary
Script shall not check after rcl level, instead it shall check after max energy at lower rc s.
### Description of issue:

Claiming , and guarding would work better, if are dependent to max energy. Both claiming and guarding blocks the colony from spawning at RCL3, without extensions.

### Error message:

```
// Console output:

```

### Other information:
- Overmind version: *{you can find this in package.json}*
    - Commit hash: *{optional, but helpful: include the commit hash (if known)}*

**Comment by bencbartlett** [comment]
As of several commits ago, the hatchery checks that it has enough energy capacity to produce anything enqueued to it using [`this.canSpawn()`](https://github.com/bencbartlett/Overmind/blob/8ab00b571f84901d5939e0f9653b642b573e48b9/src/hiveClusters/hatchery.ts#L301), so I don't think the issue you're describing can occur. Are you still finding that in the most recent commit, claimers and guards block the spawning queue at RCL3?

**Comment by paralyser** [comment]
I will try out with the latest. But 1 day ago it was an issue.

**Comment by bencbartlett** [comment]
This was fixed in [this commit](https://github.com/bencbartlett/Overmind/commit/eada14f73a161ff3afb0513f8dd51d178427eba6). Thanks for pointing it out!
