### ISSUE TITLE
Crash after claim.

### ISSUE THREAD

**Issue by paralyser** [bencbartlett/Overmind#32]
## Issue summary
Crash report
### Description of issue:

The script is crashing right after claiming a new colony. I had this issue twice in a row. I am not sure if this affects players with multiple rooms or not. 
  Beginning: I respawned in a new novice zone. I waited until my rcl hit lvl 3, and had enough extensions to create a claimer. I put a purple/grey flag in a nearby room. As soon as the claimer arrived to the room, and took it, the script crashed, with the following errors**( First error)**.

I couldn`t resolve the crash, tried loading older versions , other scripts, nothing helped, so I decided to unclaim the room( the script was still crashing). After unclaiming the room, I had the following crash errors **(second error):**

Nothing helped, so I decided to respawn. I followed exactly the above steps again, and the script crashed again, at same point, with the same error messages.

### Steps to reproduce:

1. Respawn( to make sure You have only 1 room)
2. Wait until rc3 is built , and extensions are built
3. Try to colonize a room.

### Error message:

**First error:**

`TypeError: Cannot read property 'lookForStructure' of null
    at Colony.registerUtilities (main:18803:41)
    at new Colony (main:18692:14)
    at _Overmind.registerColonies (main:21719:1605)
    at _Overmind.build (main:21719:2220)
    at main (main:21851:18)
    at Object.wrap (main:2271:12)
    at Object.loop (main:21863:21)
    at __mainLoop:1:52
    at __mainLoop:2:3`

**Second error:**

`[06:13:22][shard2]Error: Could not access room W21S56
   at Object.findClosestByRange (<runtime>:14879:19)
   at Colony.registerUtilities (main:18799:39)
   at new Colony (main:18692:14)
   at _Overmind.registerColonies (main:21719:1605)
   at _Overmind.build (main:21719:2220)
   at main (main:21851:18)
   at Object.wrap (main:2271:12)
   at Object.loop (main:21863:21)
   at __mainLoop:1:52`

// Console output:

```


### Other information:
- Overmind version: *0.4.1*
    - Commit hash: *Latest commit 700139e*

**Comment by bencbartlett** [comment]
I tried to reproduce this problem on a private server but I couldn’t get it to work. Could you try to reproduce the issue on a private server, then once it is giving the error message, close the app and send me the `Screeps/server/db.json` file, along with a copy of your `main.js`?

**Comment by paralyser** [comment]
Now I am running You absolutely unmodified main.js. Can't reproduce.

**Comment by bencbartlett** [comment]
After a lot of bug-searching and hair-pulling, this has been resolved in [the latest commit](https://github.com/bencbartlett/Overmind/commit/d4a273f5094ac82781653d8459c9507f824e8667). Thanks for pointing this out!
