### ISSUE TITLE
Overmind prioritizes creating a Queen over bootstrapping a new spawn

### ISSUE THREAD

**Issue by Kintar** [bencbartlett/Overmind#33]
### Description of issue:
When starting fresh with a new spawn, Overmind creates a queen as its first step.  The behavior I would expect from the documentation is for the room's colony to enter emergency recovery mode with a DirectiveBootstrap.  

### Steps to reproduce:
Start a fresh private server.  Spawn and load up Overmind.  Overmind will immediately begin spawning a Queen.

### Error message:
N/A

### Other information:
- Overmind version: 0.4.1
    - 52ced38

**Comment by Kintar** [comment]
FYI : If you neuter the main loop, respawn, place an orange/orange flag, and THEN push Overmind, the colony bootstraps as expected.

**Comment by bencbartlett** [comment]
Should be fixed in [this commit](https://github.com/bencbartlett/Overmind/commit/5ae121c8468ef6be43babbaea20150ce9acc8164); thanks!
