### ISSUE TITLE
Collection of mineral levels

### ISSUE THREAD

**Issue by Coolfeather2** [bencbartlett/Overmind#36]
## Feature request summary
Collect stats of each mineral and energy in the colonies + grafana dash panel.
I'm sure you are already calculating these levels for the terminal network equalize - just needs stat logging

### Motivation:

I would like to see the overall levels of resources.

### Description:

Stat collection of the levels of minerals and energy in each colony

**Comment by bencbartlett** [comment]
I've actually already added this! Global mineral assets and more detailed tradeNetwork stats will be included in the next commit when I update the dashboard JSON. (I think I'm going to move it to its own separate repository)
