### ISSUE TITLE
Pioneers getting hurt in SK rooms on their way to new baby colony

### ISSUE THREAD

**Issue by MaggNorway** [bencbartlett/Overmind#37]
### Description of issue:
When claiming a new room on the other side of SK rooms, the creeps originating from the supporting rooms can be hurt on the way thru the SK rooms, such that they arrive w/o WORK parts.

### Steps to reproduce:
Establish a new colony on the other side of a few SK rooms, ensuring the path thru them leads the support creeps to get attacked by SKs

### Error message:

```
// Console output:

```

### Other information:
- Overmind version: 0.5.0
    - Commit hash: 01f686c4250240602265e766bbc5aaeebea711df

**Comment by bencbartlett** [comment]
Fixed in [this commit](https://github.com/bencbartlett/Overmind/commit/b2fccf63491c6d124ab6a635ccfce0ea993ee694).
