### ISSUE TITLE
Ill placed bunker

### ISSUE THREAD

**Issue by MaggNorway** [bencbartlett/Overmind#43]
### Description of issue:

Sometimes bunkers are placed too close to the exits, resulting in Invaders being able to get inside the bunker while at lower RCLs and first triggering safe mode and then triggering EVAC when safe mode is on cooldown. This happens even if there is room for the bunker further from the exit.

### Steps to reproduce:

This has happened in several rooms on my private server

### Error message:

![screenshot-20180826145947-717x692](https://user-images.githubusercontent.com/7836813/44628486-b2595480-a940-11e8-9b9f-027a35b5195a.png)

```
// Offending line:

```

### Suggested fix (optional):

Attempting to place the bunker further from the edge, if it contains an exit within the planned ramparted area.

### Other information:
- Overmind version: git
    - Commit hash: *68cab1b30ed40ecc82780da17469eca342379f6a

**Comment by bencbartlett** [comment]
This is being actively worked on and should be fixed in the next few commits.

**Comment by bencbartlett** [comment]
This has been fixed in [this commit](https://github.com/bencbartlett/Overmind/commit/8ed9439d6db5686d4f2796c9e77893d99bced682).
