### ISSUE TITLE
this.room.hostiles undefined in ArcherDefenseOverlord with no room visibility

### ISSUE THREAD

**Issue by rooklion** [bencbartlett/Overmind#5]
### Description of issue:
Using the invasion defense flag (orange/red) in a room with an NPC invasion when there is no visibility throws an error on "this.room.hostiles" because "this.room" is undefined.  This error occurs in a few blocks of the ArcherDefenseOverlord class.

### Steps to reproduce:
Create an invasion defense flag (orange/red) and have no visibility in the room

### Error message:
main:9663
            amount = _.sum(_.map(this.room.hostiles, hostile => hostile.boosts.length > 0 ? 2 : 1));
                                           ^

TypeError: Cannot read property 'hostiles' of undefined
    at ArcherDefenseOverlord.init (main:9663:44)
    at Overseer.init (main:9805:26)
    at Colony.init (main:14135:23)
    at Overmind.init (main:17613:39)
    at main (main:17778:14)
    at Object.wrap (main:3682:12)
    at Object.loop (main:17785:21)
    at __mainLoop:1:52``

### Other information:
- Overmind version: 0.2
    - Commit hash: {Please include the commit hash if known}
- Issue is with dependency: no

**Comment by bencbartlett** [comment]
This is intended behavior; invasion defense flags are automatically placed by the overseer and only work in owned rooms, not outposts. (That is what guard directives are for.)
