### ISSUE TITLE
CombatOverlord incorrectly looking at this.colony for SpawnGroup boosting

### ISSUE THREAD

**Issue by rooklion** [bencbartlett/Overmind#54]
## Issue summary
Creeps belonging to a CombatOverlord aren't looking at the proper colony when trying to boost

### Description of issue:

Creeps belonging to CombatOverlords are creating a SpawnGroup but then `getBoostLab` and `handleBoosting` are looking at `Overlord.colony` instead of the colony the creep is spawning in for boosts.

### Steps to reproduce:

Create a combat directive requiring boosts (Swarm Destroyer) in range of multiple, owned colonies that would cause different colonies to all spawn creeps for the directive.

### Error message:

```
// Console output:

```

```
// Offending line:

```

### Suggested fix (optional):

in getBoostLabFor():
	//let closestLab = creep.pos.findClosestByRange(this.colony.labs);
	let closestLab: any;
	if (Overmind.colonies[creep.pos.roomName]) 
                                  closestLab = creep.pos.findClosestByRange(Overmind.colonies[creep.pos.roomName].labs);

in handleBoosting():

let boostColony = Overmind.colonies[boostLab.pos.roomName];
	if (boostColony) {
		//if (this.colony.evolutionChamber.queuePosition(creep, boostLab) == 0) {
		if (boostColony.evolutionChamber.queuePosition(creep, boostLab) == 0) {

### Other information:
- Overmind version: v0.5.0
    - Commit hash: 45b8b99

**Comment by rooklion** [comment]
Ok, I tried to format the Suggested Fix into code blocks, but couldn't figure it out.  Sorry for the cancer formatting...

**Comment by bencbartlett** [comment]
This has been (mostly) fixed in the [new boosting protocol](https://github.com/bencbartlett/Overmind/commit/4cf728965b627948d9c4a620b5734b5810eb152b) introduced after the removal of in-spawn boosting.
