### ISSUE TITLE
Shoud I ignore the TSlint?

### ISSUE THREAD

**Issue by LokiSharp** [bencbartlett/Overmind#58]
## Issue summary
When I open this code with WebStorm, here are alot of TSlint Error nearly every line.
![image](https://user-images.githubusercontent.com/2725648/49350641-a1ac3d80-f6ea-11e8-94d9-1644e8c9898b.png)

### Error message:

```
// Console output:

```

```
// Offending line:

```

### Other information:
- Overmind version: *{found in package.json or by typing `info()` into console}*
    - Commit hash: *{optional, but helpful: include the commit hash (if known)}*

**Comment by bencbartlett** [comment]
Yes, this project doesn't conform to all default tslint rules.
