### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by paralyser** [bencbartlett/Overmind#6]
### Description of Suggestion:
Atm, our screeps are using resources to build and maintain containers , near minerals, and also they have an extra bodypart (carry), which can be removed, so we spare some minerals.
I think would be considerable to get rid of the extra body part, and containers. 
 Suggestion:
 We can make miners , without carry bodypart, which empties the extracted minerals to the ground, making a stockpile. Our carrriers can pick up from there. ( saw in TooAngels AI )

Please don`t take this suggestion as an offend. I am glad to use this Ai as it is. 
Thanks for your hard work, and effort.

Machinarium

**Comment by bencbartlett** [comment]
> also they have an extra bodypart (carry), which can be removed, so we spare some minerals.

Carry is necessary to repair containers at miningSites. The extra work part (6/5) allows for full saturation of the source even if transporters are occasionally late picking up from the site and it experiences some downtime (full output).

> We can make miners , without carry bodypart, which empties the extracted minerals to the ground, making a stockpile.

Dropped resources decay at `ceil(drop.amount/1000)` per tick, so this would result in ~10% of all energy harvested being wasted.
