### ISSUE TITLE
drone / worker logic addition

### ISSUE THREAD

**Issue by Greg-Tarr** [bencbartlett/Overmind#61]
## Feature request summary
drone / worker logic addition:

If resource is on ground && source empty && container near, pickup resource, place in container.

This is to prevent decay.

**Comment by bencbartlett** [comment]
This is really only an issue in the few ticks following when containers get built for the very first time at RCL3. Mining overlords make up the plurality of CPU use by all overlords, so I am very hesitant to add any extra computational weight to them, especially when the payoff is a one-time saving of <1000 energy. I'm closing this issue, but if you can think of a more compelling scenario to justify this, I'll consider reopening.
