### ISSUE TITLE
Invasion defense flag BUG? RC2

### ISSUE THREAD

**Issue by paralyser** [bencbartlett/Overmind#7]
### Description of issue:
Invasion defense flag blocks spawn, to spawn screeps ( miners, workers, guard squad) on low lvl rc (2). If flag removed spawn will start working again, until flag is placed again.

### Steps to reproduce:
Spawn in a room , where other players screeps are passing by

### Error message:
 "N/A" 
```
// Console output:

```

### Other information:
- Overmind version: {0.2.0 - compiled 2018. May.9 - 11.00 AM ( Cest)

**Comment by bencbartlett** [comment]
Ah, thank you for pointing this out! This has been fixed in the latest release.
