### ISSUE TITLE
shard3 W11N18 breaks Overmind logic

### ISSUE THREAD

**Issue by Arygnam** [bencbartlett/Overmind#74]
### Description of issue:
Manually placing a flag at RCL3 is throwing off an undefined type error - this is using the current master compilation. I double checked the code for savedSources (which the memory.room.src property is set to) and it appears to be exactly the same as in the 5.2.1 release; I'm not sure if that version shares the same bug. On a possibly related note, the overseer hasn't automatically placed even a single outpost on any surrounding room, so it's possible the entire method for this is broken and I only see that error because I placed the flag manually.

### Steps to reproduce:
Compile current master
spawn in a fresh room
get to RCL3 and manually place a purple/purple outpost flag.

### Error message:

```
// Console output:

[2:31:21 AM]
[shard3]
INFO    4853168 Colony W11N18 assigned to Flag1.
[2:35:35 AM]
[shard3]
TypeError: Cannot read property 'src' of undefined
    at _.sum.roomName (main:25104:86)
    at arraySum (<runtime>:17624:20)
    at Function.sum (<runtime>:27925:11)
    at Overseer.handleNewOutposts (main:25104:28)
    at Overseer.placeDirectives (main:25137:22)
    at Overseer.run (main:25228:18)
    at _Overmind.run (main:25322:7133)
    at main (main:25716:14)
    at Object.wrap (main:969:16)

<!--- Please copy the line from main.js causing the error. This will be in the second line of the traceback --->
```
// Offending line:

let numSources = _.sum(colony.roomNames, roomName => (Memory.rooms[roomName].src || []).length);

### Other information:
- Overmind version: 0.5.2 (compiled master, not public release)

**Comment by Arygnam** [comment]
Alright; I couldn't find anything explicitly wrong in the code - especially given nothing about the logic has changed, other then using some of it in the new swarm behavior - so I popped in the normal 5.2.1 release just to double check; and found I was having the same issue.

Furthermore, upon entering RCL4 the queen stopped filling the last two or three extensions, keeping the spawn capped at around 1100 energy +-50 or so; which eventually lead to the time to live code not able to fulfill replacing existing screeps to the point where the colony ended up in bootstrap mode which did work, but only temporarily as the new queen repeated the same behavior.

I found it doubtful that this behavior was intentional, so I popped my spawn and claim and started anew.

Sure enough, moving back to the current compiled master and in a different room, Overmind returned to working flawlessly.

Something about that room W11N18 in shard3 completely breaks the logic of Overmind in an unrecoverable manner - making this a much more specific use case scenario.

**Comment by bencbartlett** [comment]
I think the `TypeError: Cannot read property 'src' of undefined` has been fixed in a commit recently. The offending line was probably [this](https://github.com/bencbartlett/Overmind/blob/master/src/Overseer.ts#L269). The behavioral problems you mentioned might be related to the fact that there are impassible newbie walls surrounding several sides of that room, and Overmind generally doesn't deal with newbie zones well. However, I'm not sure why that should cause queens to not refill structures as needed... Try moving back into the room once the newbie zone comes down and see if it still has this problem.

**Comment by bencbartlett** [comment]
Closing due to lack of response.
