### ISSUE TITLE
Shard market history saved 

### ISSUE THREAD

**Issue by Coolfeather2** [bencbartlett/Overmind#86]
## Feature request summary
Create a "Stock market" stats 

### Motivation:

Would be useful for the overmind marketing logic

### Description:

we could add a stock market feature to grafana maybe?
get the current market orders and log it to stats every 15ish?
only problem then would be pushing it back to screeps
unless we keep x days in memory summarized like:
Keep every point of the last ~1h
Summarize points into 1h blocks <1h ago
Summarize points into 1d blocks <24h ago
Remove points <7d

maybe ags131 has a grafana dashboard for that already and people could add it to their dash? idk

### Related issues:

DKPLUGINS is actively poisioning the bid price on shard 1 for eth0nic. DKPLUGINS creates tiny orders overmind then has to "beat", and then removes them.

Muon is aware that was a potential issue, but I don’t have a super great way to get around it.

**Comment by bencbartlett** [comment]
Stock market code is being rewritten
