### ISSUE TITLE
Colony freezes if creep on construction site

### ISSUE THREAD

**Issue by rooklion** [bencbartlett/Overmind#9]
### Description of issue:
If a priority construction site is generated under a worker creep (maybe another type?), the entire colony will freeze because of -7 error on building.

### Steps to reproduce:
Have a room reach level 3 while a creep is standing where a tower construction site is placed.  All workers fail at building which freezes the colony but prevents the worker from moving off the site.

Problem fixed after moving the offending creep off the position.

### Error message:
N/A
// Console output:
N/A

### Other information:
- Overmind version: 0.3.1
    - Commit hash: c01ab8a902da8406a1ccd84dbb058434925a7bd3
- Issue is with dependency: no

**Comment by bencbartlett** [comment]
What do you mean by "the colony freezes"? Do all creeps in the colony stop operating or do only workers stop operating? How long does this effect last for? Typically if the room planner can't place a constructionSite, it will log an error in the console but continue working as normal.

**Comment by rooklion** [comment]
Ok after reviewing the room history, it appears that only the workers were affected, but since they weren't doing anything, the miners filled the containers, the transporters had no output.  Here is a link to the history:
screeps.com/s/AqP1f7

**Comment by bencbartlett** [comment]
Forgot to close this issue - this was fixed recently: https://github.com/bencbartlett/Overmind/blob/master/src/overlords/core/overlord_work.ts#L122
