### ISSUE TITLE
NCP should perform some work to justify getting the resourses they're getting

### ISSUE THREAD

**Issue by inakrin** [bencbartlett/Overmind#94]
## Feature request summary
The NCP (non-coding players should perform some work to justify the resources they're getting)
### Motivation:

Nowadays anyone can spawn the bot and get boosts, bases, and gcl without performing any  actual work.  That's unfair for the players who're actually spend nights and days putting their minds into the code, typing, making mistakes, breaking everything and typing again. Also since the overmind users are not experienced in programming and have not achieved the enlightenment of having written at least a working thing thing themselves would be good to put some educational purpose in their game.

### Description:

So. Basically the idea is that since the most annoying part of any programmer's life is typing, let's start from it. The first resource the ovemind's spawners are eager to get is rcl&gcl. So the bot should be coded in a way that any 100K-1M of rcl/gcl the bot should stop working until the NCP performs a typing task assigned to him.  The tasks could be for example: type geometric progression of y members with ratio x. Or type comma-separated factorials of numbers from x to y.  Each in-game significant action should be locked to a certain task. Higher the level of the achievment - more complicated is the task. For example for sending an offensive team to a neighbour let's say a user has to type in the console the prime numbers which meet the code-generated requirement. (They should be pretty long and in case of boosted team they should have somehow have the boost names coded in them). 
That will make the game fair and pleasant to everybody!

**Comment by GuguKatze** [comment]
Enter Rayo's number into your console in order to unlock a team of virtual spheres in a pointless game.

**Comment by sdk2013** [comment]
> 
> 
> Enter Rayo's number into your console in order to unlock a team of virtual spheres in a pointless game.

If it's pointless, then why are you here? Hmm?

**Comment by bencbartlett** [comment]
No.
